/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.component;

/**
 *
 * @author haidu
 */
public class Header_main extends javax.swing.JFrame {

    /**
     * Creates new form Header_main
     */
    public Header_main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        trangsuccuoi_label = new javax.swing.JLabel();
        dongho_label = new javax.swing.JLabel();
        quatang_label = new javax.swing.JLabel();
        thuonghieu_label = new javax.swing.JLabel();
        bosuutap_label = new javax.swing.JLabel();
        khuyenmai_label = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        contact_label = new javax.swing.JLabel();
        store_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(190, 162, 136));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logo_bt.png"))); // NOI18N

        trangsuccuoi_label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        trangsuccuoi_label.setForeground(java.awt.Color.white);
        trangsuccuoi_label.setText("Trang sức cưới");

        dongho_label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        dongho_label.setForeground(java.awt.Color.white);
        dongho_label.setText("Đồng hồ");

        quatang_label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        quatang_label.setForeground(java.awt.Color.white);
        quatang_label.setText("Quà tặng");

        thuonghieu_label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        thuonghieu_label.setForeground(java.awt.Color.white);
        thuonghieu_label.setText("Thương hiệu");

        bosuutap_label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        bosuutap_label.setForeground(java.awt.Color.white);
        bosuutap_label.setText("Bộ sưu tập");

        khuyenmai_label.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        khuyenmai_label.setForeground(java.awt.Color.white);
        khuyenmai_label.setText("Khuyến mãi");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);

        contact_label.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        contact_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/contact.png"))); // NOI18N
        contact_label.setText("1800.1410.2024");

        store_label.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        store_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/map.png"))); // NOI18N
        store_label.setText("Cửa hàng");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(logo)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1192, 1192, 1192)
                        .addComponent(jLabel10)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(trangsuccuoi_label)
                        .addGap(66, 66, 66)
                        .addComponent(dongho_label)
                        .addGap(71, 71, 71)
                        .addComponent(quatang_label)
                        .addGap(63, 63, 63)
                        .addComponent(thuonghieu_label)
                        .addGap(52, 52, 52)
                        .addComponent(bosuutap_label)
                        .addGap(60, 60, 60)
                        .addComponent(khuyenmai_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                        .addComponent(store_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(contact_label)
                        .addGap(40, 40, 40))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(logo)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(trangsuccuoi_label)
                                    .addComponent(dongho_label)
                                    .addComponent(quatang_label)
                                    .addComponent(thuonghieu_label)
                                    .addComponent(bosuutap_label)
                                    .addComponent(khuyenmai_label))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(contact_label)
                                    .addComponent(store_label)))
                            .addGap(38, 38, 38)))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Header_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Header_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Header_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Header_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Header_main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bosuutap_label;
    private javax.swing.JLabel contact_label;
    private javax.swing.JLabel dongho_label;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel khuyenmai_label;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel quatang_label;
    private javax.swing.JLabel store_label;
    private javax.swing.JLabel thuonghieu_label;
    private javax.swing.JLabel trangsuccuoi_label;
    // End of variables declaration//GEN-END:variables
}
