/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.component;

import java.awt.Color;

/**
 *
 * @author haidu
 */
public class Menu extends javax.swing.JPanel {

    private com.raven.swing.Button2 isSelect ;
     
    
    private final Color DefaultColor;
    private final Color ClickedColor;
    
    public Menu() {
        initComponents();
         // Khởi tạo màu mặc định
    DefaultColor = new Color(255,255,255);
    ClickedColor = new Color(190,162,136);
    }
    
    private void changeButtonState(com.raven.swing.Button2 selectedButton) {
    // Đặt màu cho các nút
    button21.setBackground(DefaultColor);
    button22.setBackground(DefaultColor);
    button23.setBackground(DefaultColor);
    button24.setBackground(DefaultColor);
    button25.setBackground(DefaultColor);
    button26.setBackground(DefaultColor);
    button27.setBackground(DefaultColor);
    button28.setBackground(DefaultColor);

    // Đặt nút được chọn thành màu clicked
    selectedButton.setBackground(ClickedColor);

    // Đặt các nút còn lại thành enabled = true
    button21.setEnabled(true);
    button22.setEnabled(true);
    button23.setEnabled(true);
    button24.setEnabled(true);
    button25.setEnabled(true);
    button26.setEnabled(true);
    button27.setEnabled(true);
    button28.setEnabled(true);

    // Đặt nút được chọn thành enabled = false
    selectedButton.setEnabled(false);

    // Lưu nút được chọn vào thuộc tính isSelect
    isSelect = selectedButton;
}
// Sử dụng hàm trên trong các sự kiện của các nút


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        button21 = new com.raven.swing.Button2();
        button22 = new com.raven.swing.Button2();
        button23 = new com.raven.swing.Button2();
        button24 = new com.raven.swing.Button2();
        button25 = new com.raven.swing.Button2();
        button26 = new com.raven.swing.Button2();
        button27 = new com.raven.swing.Button2();
        button28 = new com.raven.swing.Button2();

        setBackground(new java.awt.Color(255, 255, 255));

        button21.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        button21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu1.png"))); // NOI18N
        button21.setText("Trang chủ");
        buttonGroup1.add(button21);
        button21.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        button21.setIconTextGap(15);
        button21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button21ActionPerformed(evt);
            }
        });

        button22.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        button22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu2.png"))); // NOI18N
        button22.setText("Trang sức cưới");
        buttonGroup1.add(button22);
        button22.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        button22.setIconTextGap(15);
        button22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button22ActionPerformed(evt);
            }
        });

        button23.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        button23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu3.png"))); // NOI18N
        button23.setText("Đồng hồ");
        buttonGroup1.add(button23);
        button23.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        button23.setIconTextGap(15);
        button23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button23ActionPerformed(evt);
            }
        });

        button24.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        button24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu4.png"))); // NOI18N
        button24.setText("Quà tặng");
        buttonGroup1.add(button24);
        button24.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        button24.setIconTextGap(15);
        button24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button24ActionPerformed(evt);
            }
        });

        button25.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        button25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu5.png"))); // NOI18N
        button25.setText("Thương hiệu");
        buttonGroup1.add(button25);
        button25.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        button25.setIconTextGap(15);
        button25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button25ActionPerformed(evt);
            }
        });

        button26.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        button26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu6.png"))); // NOI18N
        button26.setText("Bộ sưu tập");
        buttonGroup1.add(button26);
        button26.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        button26.setIconTextGap(20);
        button26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button26ActionPerformed(evt);
            }
        });

        button27.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 7, 1, 1));
        button27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu7.png"))); // NOI18N
        button27.setText("Livestream");
        buttonGroup1.add(button27);
        button27.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        button27.setIconTextGap(13);
        button27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button27ActionPerformed(evt);
            }
        });

        button28.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        button28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu8.png"))); // NOI18N
        button28.setText("KHTT");
        buttonGroup1.add(button28);
        button28.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        button28.setIconTextGap(15);
        button28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button28ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(button21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(button22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(button23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(button24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(button25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(button26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(button27, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
            .addComponent(button28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(button21, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button22, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button23, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button24, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button25, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button26, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button27, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button28, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 93, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void button21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button21ActionPerformed
        changeButtonState(button21);
    }//GEN-LAST:event_button21ActionPerformed

    private void button22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button22ActionPerformed
        changeButtonState(button22);
    }//GEN-LAST:event_button22ActionPerformed

    private void button23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button23ActionPerformed
        changeButtonState(button23);
    }//GEN-LAST:event_button23ActionPerformed

    private void button24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button24ActionPerformed
        changeButtonState(button24); 
    }//GEN-LAST:event_button24ActionPerformed

    private void button25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button25ActionPerformed
        changeButtonState(button25);
    }//GEN-LAST:event_button25ActionPerformed

    private void button26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button26ActionPerformed
        changeButtonState(button26);
    }//GEN-LAST:event_button26ActionPerformed

    private void button27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button27ActionPerformed
        changeButtonState(button27);
    }//GEN-LAST:event_button27ActionPerformed

    private void button28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button28ActionPerformed
        changeButtonState(button28);
    }//GEN-LAST:event_button28ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.swing.Button2 button21;
    private com.raven.swing.Button2 button22;
    private com.raven.swing.Button2 button23;
    private com.raven.swing.Button2 button24;
    private com.raven.swing.Button2 button25;
    private com.raven.swing.Button2 button26;
    private com.raven.swing.Button2 button27;
    private com.raven.swing.Button2 button28;
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables
}
